### ISSUE TITLE
SVG Error

### ISSUE THREAD

**Issue by RobotZwrrl** [jasonwebb/2d-voronoi-experiments#1]
Hi Jason,
Really enjoy this experiment - thanks for putting it up online and making it open source for many to enjoy!
It seems there's an error encountered with the SVG, when trying to open it in Illustrator it says 'this SVG is invalid'. Opening in Chrome gives some more info:

```
This page contains the following errors:
error on line 2 at column 78: Attribute xmlns redefined
```

Removing the first xmlns in the line 2 seems to work

```
Remove this:
xmlns="http://www.w3.org/1999/xhtml"
```

Thanks!

**Comment by jasonwebb** [comment]
Darn, sorry about that! I can confirm the issue on Chrome on my Win10 machine too. I have a hunch that there was a Chrome update between now and when I published this app that is causing the export functionality to work a little differently. I'll get it patched ASAP!

**Comment by jasonwebb** [comment]
Fixed! If you are still having problems, just open this issue back up and let me know )
